### ISSUE TITLE
[SDK] __vite_ssr_import_1__.default.fromBuffer is not a function

### ISSUE THREAD

**Issue by AbdurrehmanSubhani** [UpstreetAI/upstreet-core#628]
Steps to reproduce:

- Create an agent having the Discord component setup
- Ask the agent to generate a video

```
 abdurrehmansubhani@Abdurrehmans-MacBook-Pro monorepo %   usdk chat /Users/abdurrehmansubhani/Desktop/agents/discordAgent3 -g
discord connect 1
discord connect 1
You are "Subhani" [a55342c2-e0c4-4f61-87ae-d1e017b7e687]), chatting in room:O3GZsBGy.
* Echo Warrior [42a9019a-4b6f-4961-b424-042aa564d938] 
* Subhani [a55342c2-e0c4-4f61-87ae-d1e017b7e687] (you)
Subhani (you): discord connect 2
discord connect 3 {
  connectableChannels: [ 'general', 'General' ],
  connectableDms: [ 'MonitoRSS', 'Subhani', 'Midjourney Bot', 'FinanceBot', 'MyBot' ],
  userWhitelist: undefined
}

Subhani (you): discord connect 4
discord connect 5
text message {
  userId: '343797252914937856',
  username: 'subhani',
  text: 'Hey there',
  channelId: '1089397187559047282'
}
text message {
  userId: '343797252914937856',
  username: 'subhani',
  text: 'going good whats up on your mind',
  channelId: '1089397187559047282'
}
text message {
  userId: '343797252914937856',
  username: 'subhani',
  text: 'sounds good',
  channelId: '1089397187559047282'
}
generating monologue for {
  monologueString: 'The following error occurred while generating the media:\n' +
    '\n' +
    `{"type":"model/video/mp4+video","prompt":"a mystical landscape with glowing caves and shimmering waterfalls","chatText":"Here's a glimpse of our enchanted destination. Let's uncover its secrets together! 🌌✨"}\n` +
    '\n' +
    'TypeError: __vite_ssr_import_1__.default.fromBuffer is not a function\n' +
    '    at blob2jimp (/Users/abdurrehmansubhani/Desktop/agents/discordAgent3/packages/upstreet-agent/packages/react-agents/util/generate-video.mjs:6:28)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n' +
    '    at async Module.generateVideo (/Users/abdurrehmansubhani/Desktop/agents/discordAgent3/packages/upstreet-agent/packages/react-agents/util/generate-video.mjs:36:17)\n' +
    '    at async Object.generate (/Users/abdurrehmansubhani/Desktop/agents/discordAgent3/packages/upstreet-agent/packages/react-agents/default-components.tsx:1270:25)\n' +
    '    at async handler (/Users/abdurrehmansubhani/Desktop/agents/discordAgent3/packages/upstreet-agent/packages/react-agents/default-components.tsx:1358:28)\n' +
    '    at async Promise.all (index 0)\n' +
    '    at async Module.executeAgentActionStep (/Users/abdurrehmansubhani/Desktop/agents/discordAgent3/packages/upstreet-agent/packages/react-agents/runtime.ts:341:7)\n' +
    '    at async eval (/Users/abdurrehmansubhani/Desktop/agents/discordAgent3/packages/upstreet-agent/packages/react-agents/classes/generative-agent-object.ts:90:11)\n' +
    '    at async ConversationObject.typing (/Users/abdurrehmansubhani/Desktop/agents/discordAgent3/packages/upstreet-agent/packages/react-agents/classes/conversation-object.ts:78:14)\n' +
    '    at async eval (/Users/abdurrehmansubhani/Desktop/agents/discordAgent3/packages/upstreet-agent/packages/react-agents/classes/generative-agent-object.ts:87:7)'
}
text message {
  userId: '343797252914937856',
  username: 'subhani',
  text: 'sounds good',
  channelId: '1089397187559047282'
}
text message {
  userId: '343797252914937856',
  username: 'subhani',
  text: 'can you generate me an image though?',
  channelId: '1089397187559047282'
}
```

**Comment by AbdurrehmanSubhani** [comment]
Updated the Jimp version to the latest

**Comment by AbdurrehmanSubhani** [comment]
https://github.com/UpstreetAI/monorepo/pull/631
