### ISSUE TITLE
[SDK] generate video throwing error

### ISSUE THREAD

**Issue by AbdurrehmanSubhani** [UpstreetAI/upstreet-core#632]
Steps to repro:

- ask agent to generate a video
- exception thrown:

```
error resizing image ZodError: [
  {
    "code": "invalid_union",
    "unionErrors": [
      {
        "issues": [
          {
            "code": "invalid_type",
            "expected": "object",
            "received": "number",
            "path": [],
            "message": "Expected object, received number"
          }
        ],
        "name": "ZodError"
      },
      {
        "issues": [
          {
            "code": "invalid_type",
            "expected": "object",
            "received": "number",
            "path": [],
            "message": "Expected object, received number"
          }
        ],
        "name": "ZodError"
      }
    ],
    "path": [],
    "message": "Invalid input"
  }
]
    at get error (file:///Users/abdurrehmansubhani/Desktop/agents/discordAgent4/node_modules/zod/lib/index.mjs:587:31)
    at ZodUnion.parse (file:///Users/abdurrehmansubhani/Desktop/agents/discordAgent4/node_modules/zod/lib/index.mjs:692:22)
    at Object.resize (/Users/abdurrehmansubhani/Desktop/agents/discordAgent4/node_modules/@jimp/plugin-resize/src/index.ts:81:42)
    at Jimp.Jimp.<computed> (/Users/abdurrehmansubhani/Desktop/agents/discordAgent4/node_modules/@jimp/core/src/index.ts:200:42)
    at Module.generateVideo (/Users/abdurrehmansubhani/Desktop/agents/discordAgent4/packages/upstreet-agent/packages/react-agents/util/generate-video.mjs:40:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Object.generate (/Users/abdurrehmansubhani/Desktop/agents/discordAgent4/packages/upstreet-agent/packages/react-agents/default-components.tsx:1271:25)
    at async handler (/Users/abdurrehmansubhani/Desktop/agents/discordAgent4/packages/upstreet-agent/packages/react-agents/default-components.tsx:1360:28)
    at async Promise.all (index 0)
    at async Module.executeAgentActionStep (/Users/abdurrehmansubhani/Desktop/agents/discordAgent4/packages/upstreet-agent/packages/react-agents/runtime.ts:341:7) {
  issues: [
    {
      code: 'invalid_union',
      unionErrors: [Array],
      path: [],
      message: 'Invalid input'
    }
  ],
  addIssue: [Function (anonymous)],
  addIssues: [Function (anonymous)],
  errors: [
    {
      code: 'invalid_union',
      unionErrors: [Array],
      path: [],
      message: 'Invalid input'
    }
  ]
}
```

**Comment by AbdurrehmanSubhani** [comment]
Fix added in the following PR:
https://github.com/UpstreetAI/monorepo/pull/633
