### ISSUE TITLE
[Discord] Audio file is too short error

### ISSUE THREAD

**Issue by AbdurrehmanSubhani** [UpstreetAI/upstreet-core#637]
Steps to repro:

- Ensure Discord bot is setup, running and available in a voice chat
- Talk to the agent

Exception logs:

```
    at Module.transcribe (/Users/abdurrehmansubhani/Desktop/agents/discordAgent6/packages/upstreet-agent/packages/react-agents/util/audio-perception.mjs:111:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async eval (/Users/abdurrehmansubhani/Desktop/agents/discordAgent6/packages/upstreet-agent/packages/react-agents/lib/discord/discord-client.js:285:20)
    at async fn2 (/Users/abdurrehmansubhani/Desktop/agents/discordAgent6/packages/upstreet-agent/packages/queue-manager/queue-manager.mjs:96:20)
    at async QueueManager.#waitForTurnEntry (/Users/abdurrehmansubhani/Desktop/agents/discordAgent6/packages/upstreet-agent/packages/queue-manager/queue-manager.mjs:59:18)
Error: request failed: 400: {
  "error": {
    "message": "Audio file is too short. Minimum audio length is 0.1 seconds.",
    "type": "invalid_request_error",
    "param": "file",
    "code": "audio_too_short"
  }
}
```

**Comment by AbdurrehmanSubhani** [comment]
Fixed with the latest stream buffereing
