### ISSUE TITLE
[Discord] Getting got local message for unknown agent

### ISSUE THREAD

**Issue by AbdurrehmanSubhani** [UpstreetAI/upstreet-core#701]
```
got local message for unknown agent {
  message: {
    userId: '343a4994-5d53-574c-aafc-e59024899560',
    name: 'subhani',
    method: 'say',
    args: { text: [Object] },
    attachments: undefined,
    timestamp: 2024-11-28T15:08:50.234Z,
    human: false,
    hidden: false
  },
  agentsMap: Map(0) {}
} Error
    at ConversationObject.addLocalMessage (/Users/abdurrehmansubhani/Desktop/agents/discordAgent3/packages/upstreet-agent/packages/react-agents/classes/conversation-object.ts:217:10)
    at async DiscordOutput.eval (/Users/abdurrehmansubhani/Desktop/agents/discordAgent3/packages/upstreet-agent/packages/react-agents/classes/discord-manager.ts:361:11)
```

**Comment by AbdurrehmanSubhani** [comment]
not reproduced later
