### ISSUE TITLE
[Bug]: Defining the same Zod schema in different Actions throws an error

### ISSUE THREAD

**Issue by SaadBazaz** [UpstreetAI/upstreet-core#707]
### Product

USDK (Upstreet Agents SDK)

### What happened?

I'm trying to automatically generate Agent Actions from an [OpenAPI spec](https://editor.swagger.io/).

It basically does the following:
- Converts OpenAPI spec to Zod schemas using `openapi-zod-client`, and then creates a Zodios client
- Uses the Zodios client, maps over each API endpoint, and then generates an Action
- Calls all the actions in the main. 

The code is available [here](https://github.com/UpstreetAI/usdk-examples/tree/main/openApiAgent), open source.

## Problem
As mentioned before, the API's schemas are auto-generated by `openapi-zod-client`.

But API endpoints have reused the schemas.

For examples,
`addPet` and `updatePet` reuse the same `Pet` schema.

`addPet`:
https://github.com/UpstreetAI/usdk-examples/blob/main/openApiAgent/api.ts#L61

`updatePet`:
https://github.com/UpstreetAI/usdk-examples/blob/main/openApiAgent/api.ts#L84

### Version

0.0.94

### What is your environment?

Node: v22.9.0
NPM: 10.8.3
macOS Sonoma 14.6.1 (23G93)

### Relevant log output

I've played around with this and noticed that whenever a schema reappears again, in **any nested level**, in another Action, `usdk chat` throws this error:

```
think error Error: invalid status code: 400: {
  "error": {
    "message": "Invalid schema for response_format 'result'. Please ensure it is a valid JSON Schema.",
    "type": "invalid_request_error",
    "param": "response_format",
    "code": null
  }
}
    at Module.fetchJsonCompletion (/Users/saadbazaz/Projects/openapi-agent/packages/upstreet-agent/packages/react-agents/util/fetch.mjs:358:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async AppContextValue.completeJson (/Users/saadbazaz/Projects/openapi-agent/packages/upstreet-agent/packages/react-agents/classes/app-context-value.ts:193:21)
    at async GenerativeAgentObject.completeJson (/Users/saadbazaz/Projects/openapi-agent/packages/upstreet-agent/packages/react-agents/classes/generative-agent-object.ts:74:12)
    at async _generateAgentActionStepFromMessages (/Users/saadbazaz/Projects/openapi-agent/packages/upstreet-agent/packages/react-agents/runtime.ts:130:29)
    at async Module.generateAgentActionStep (/Users/saadbazaz/Projects/openapi-agent/packages/upstreet-agent/packages/react-agents/runtime.ts:109:10)
    at async eval (/Users/saadbazaz/Projects/openapi-agent/packages/upstreet-agent/packages/react-agents/classes/generative-agent-object.ts:89:24)
    at async ConversationObject.typing (/Users/saadbazaz/Projects/openapi-agent/packages/upstreet-agent/packages/react-agents/classes/conversation-object.ts:78:14)
    at async eval (/Users/saadbazaz/Projects/openapi-agent/packages/upstreet-agent/packages/react-agents/classes/generative-agent-object.ts:87:7)
    at async QueueManager.#waitForTurnEntry (/Users/saadbazaz/Projects/openapi-agent/packages/upstreet-agent/packages/queue-manager/queue-manager.mjs:59:18)
```

Screenshot:
<img width="1093" alt="Screenshot 2024-12-02 at 15 32 14" src="https://github.com/user-attachments/assets/890431ba-f30f-4b9a-ba13-2335e1e69d2a">

It seems like an issue in `JSONFormatter`.

**Comment by avaer** [comment]
I tried updating our `openai` library (which is generating these schemas) but no luck on the latest `4.74.0`.

**Comment by avaer** [comment]
My research indicates that our schema in this example is probably not compliant with openai structured outputs. For example, there is a `z.instanceof(File)` which is probably never going to work since JSON does not parse `File`, even if openai could generate some representation of File.

**Comment by AbdurrehmanSubhani** [comment]
fixed so closing
