### ISSUE TITLE
[USDK]

### ISSUE THREAD

**Issue by avaer** [UpstreetAI/upstreet-core#733]
### Product

USDK (Upstreet Agents SDK)

### What happened?

The version from `npm install -g usdk` doesn't work:

```
RangeError: Maximum call stack size exceeded

RangeError: Maximum call stack size exceeded
    at RealtimeClient._getAccessToken (/Users/og/agents/i7MIYkKM/node_modules/.pnpm/@supabase+supabase-js@2.47.0/node_modules/@supabase/supabase-js/src/SupabaseClient.ts:268:32)
    at RealtimeClient.<anonymous> (/Users/og/agents/i7MIYkKM/node_modules/.pnpm/@supabase+supabase-js@2.47.0/node_modules/@supabase/supabase-js/src/SupabaseClient.ts:270:25)
    at Generator.next (<anonymous>)
    at /Users/og/agents/i7MIYkKM/node_modules/.pnpm/@supabase+supabase-js@2.47.0/node_modules/@supabase/supabase-js/dist/main/SupabaseClient.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/og/agents/i7MIYkKM/node_modules/.pnpm/@supabase+supabase-js@2.47.0/node_modules/@supabase/supabase-js/dist/main/SupabaseClient.js:4:12)
    at RealtimeClient._getAccessToken (/Users/og/agents/i7MIYkKM/node_modules/.pnpm/@supabase+supabase-js@2.47.0/node_modules/@supabase/supabase-js/src/SupabaseClient.ts:268:32)
    at RealtimeClient.<anonymous> (/Users/og/agents/i7MIYkKM/node_modules/.pnpm/@supabase+supabase-js@2.47.0/node_modules/@supabase/supabase-js/src/SupabaseClient.ts:270:25)
    at Generator.next (<anonymous>)
    at /Users/og/agents/i7MIYkKM/node_modules/.pnpm/@supabase+supabase-js@2.47.0/node_modules/@supabase/supabase-js/dist/main/SupabaseClient.js:8:71
    ```

**Comment by SaadBazaz** [comment]
```
Exception in PromiseRejectCallback:
/Users/saadbazaz/Projects/bots-and-pieces/scillia-discord/node_modules/.pnpm/@supabase+supabase-js@2.47.0/node_modules/@supabase/supabase-js/dist/main/SupabaseClient.js:4
    return new (P || (P = Promise))(function (resolve, reject) {
           ^

RangeError: Maximum call stack size exceeded

Exception in PromiseRejectCallback:
/Users/saadbazaz/Projects/bots-and-pieces/scillia-discord/node_modules/.pnpm/@supabase+supabase-js@2.47.0/node_modules/@supabase/supabase-js/dist/main/SupabaseClient.js:7
        function step(result) { result.done ? resolve(result.value) : adopt(result.value).then(fulfilled, rejected); }
                                                                                          ^

RangeError: Maximum call stack size exceeded

RangeError: Maximum call stack size exceeded
    at <anonymous>
    at new Promise (<anonymous>)
    at __awaiter (/Users/saadbazaz/Projects/bots-and-pieces/scillia-discord/node_modules/.pnpm/@supabase+supabase-js@2.47.0/node_modules/@supabase/supabase-js/dist/main/SupabaseClient.js:4:12)
    at RealtimeClient._getAccessToken (/Users/saadbazaz/Projects/bots-and-pieces/scillia-discord/node_modules/.pnpm/@supabase+supabase-js@2.47.0/node_modules/@supabase/supabase-js/src/SupabaseClient.ts:268:32)
    at RealtimeClient.<anonymous> (/Users/saadbazaz/Projects/bots-and-pieces/scillia-discord/node_modules/.pnpm/@supabase+supabase-js@2.47.0/node_modules/@supabase/supabase-js/src/SupabaseClient.ts:270:25)
    at Generator.next (<anonymous>)
    at /Users/saadbazaz/Projects/bots-and-pieces/scillia-discord/node_modules/.pnpm/@supabase+supabase-js@2.47.0/node_modules/@supabase/supabase-js/dist/main/SupabaseClient.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/saadbazaz/Projects/bots-and-pieces/scillia-discord/node_modules/.pnpm/@supabase+supabase-js@2.47.0/node_modules/@supabase/supabase-js/dist/main/SupabaseClient.js:4:12)
    at RealtimeClient._getAccessToken (/Users/saadbazaz/Projects/bots-and-pieces/scillia-discord/node_modules/.pnpm/@supabase+supabase-js@2.47.0/node_modules/@supabase/supabase-js/src/SupabaseClient.ts:268:32)
discord bot error Error: discord status error: Error [TokenInvalid]: An invalid token was provided.
    at WebSocketManager.connect (/app/node_modules/discord.js/src/client/websocket/WebSocketManager.js:136:26)
    at Client.login (/app/node_modules/discord.js/src/client/Client.js:228:21)
    at file:///app/discord-bot.mjs:496:20
    at DiscordClient.connect (file:///app/discord-bot.mjs:498:7)
    at Server.onrequest (file:///app/discord-bot.mjs:594:31)
    at Server.emit (node:events:520:28)
    at parserOnIncoming (node:_http_server:1149:12)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
    at _connect (/Users/saadbazaz/Projects/bots-and-pieces/scillia-discord/packages/upstreet-agent/packages/react-agents/classes/discord-manager.ts:172:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async eval (/Users/saadbazaz/Projects/bots-and-pieces/scillia-discord/packages/upstreet-agent/packages/react-agents/classes/discord-manager.ts:382:7)
discord bot error Error: discord status error: Error [TokenInvalid]: An invalid token was provided.
    at WebSocketManager.connect (/app/node_modules/discord.js/src/client/websocket/WebSocketManager.js:136:26)
    at Client.login (/app/node_modules/discord.js/src/client/Client.js:228:21)
    at file:///app/discord-bot.mjs:496:20
    at DiscordClient.connect (file:///app/discord-bot.mjs:498:7)
    at Server.onrequest (file:///app/discord-bot.mjs:594:31)
    at Server.emit (node:events:520:28)
    at parserOnIncoming (node:_http_server:1149:12)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
    at _connect (/Users/saadbazaz/Projects/bots-and-pieces/scillia-discord/packages/upstreet-agent/packages/react-agents/classes/discord-manager.ts:172:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async eval (/Users/saadbazaz/Projects/bots-and-pieces/scillia-discord/packages/upstreet-agent/packages/react-agents/classes/discord-manager.ts:382:7)
You are "saadbazaz#0" [133165e1-87e1-41dd-9010-7e1d8127946e]), chatting in room:ivdSBXCp.
* AI Agent [6f277c76-3d72-44c6-9ac6-1baa88cba3f7] 
* saadbazaz#0 [133165e1-87e1-41dd-9010-7e1d8127946e] (you)
saadbazaz#0 (you): Exception in PromiseRejectCallback:
/Users/saadbazaz/Projects/bots-and-pieces/scillia-discord/node_modules/.pnpm/@supabase+supabase-js@2.47.0/node_modules/@supabase/supabase-js/dist/main/SupabaseClient.js:4
    return new (P || (P = Promise))(function (resolve, reject) {
           ^

RangeError: Maximum call stack size exceeded

Exception in PromiseRejectCallback:
/Users/saadbazaz/Projects/bots-and-pieces/scillia-discord/node_modules/.pnpm/@supabase+supabase-js@2.47.0/node_modules/@supabase/supabase-js/dist/main/SupabaseClient.js:7
        function step(result) { result.done ? resolve(result.value) : adopt(result.value).then(fulfilled, rejected); }
                                                                                          ^

RangeError: Maximum call stack size exceeded

RangeError: Maximum call stack size exceeded
    at /Users/saadbazaz/Projects/bots-and-pieces/scillia-discord/node_modules/.pnpm/@supabase+supabase-js@2.47.0/node_modules/@supabase/supabase-js/dist/main/SupabaseClient.js:4:46
    at new Promise (<anonymous>)
    at __awaiter (/Users/saadbazaz/Projects/bots-and-pieces/scillia-discord/node_modules/.pnpm/@supabase+supabase-js@2.47.0/node_modules/@supabase/supabase-js/dist/main/SupabaseClient.js:4:12)
    at RealtimeClient._getAccessToken (/Users/saadbazaz/Projects/bots-and-pieces/scillia-discord/node_modules/.pnpm/@supabase+supabase-js@2.47.0/node_modules/@supabase/supabase-js/src/SupabaseClient.ts:268:32)
    at RealtimeClient.<anonymous> (/Users/saadbazaz/Projects/bots-and-pieces/scillia-discord/node_modules/.pnpm/@supabase+supabase-js@2.47.0/node_modules/@supabase/supabase-js/src/SupabaseClient.ts:270:25)
    at Generator.next (<anonymous>)
    at /Users/saadbazaz/Projects/bots-and-pieces/scillia-discord/node_modules/.pnpm/@supabase+supabase-js@2.47.0/node_modules/@supabase/supabase-js/dist/main/SupabaseClient.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/saadbazaz/Projects/bots-and-pieces/scillia-discord/node_modules/.pnpm/@supabase+supabase-js@2.47.0/node_modules/@supabase/supabase-js/dist/main/SupabaseClient.js:4:12)
    at RealtimeClient._getAccessToken (/Users/saadbazaz/Projects/bots-and-pieces/scillia-discord/node_modules/.pnpm/@supabase+supabase-js@2.47.0/node_modules/@supabase/supabase-js/src/SupabaseClient.ts:268:32
```
   
Reproduced on fresh install.
